import { Link } from "react-router-dom";
import "../styles/About.css";

const About = () => <div className="about-page">
  <section className="about-hero"><span>Acerca del proyecto</span><h1>Una estimación que entiende el vehículo y la ruta completa.</h1><p>Travel Calculator supera las aproximaciones basadas solo en distancia y un promedio fijo. Combina rendimiento, terreno y condiciones de uso para entregar un costo más contextual y explicar qué cambió el consumo.</p><div><Link to="/calculadora">Probar la calculadora</Link><Link className="about-secondary" to="/resultado">Ver último resultado</Link></div></section>
  <section className="about-principles"><article><span>01</span><h2>Más contexto</h2><p>Vehículo, rendimiento real, peso, pasajeros, vía, clima, tráfico horario, conducción y pendientes participan en la estimación.</p></article><article><span>02</span><h2>Resultado explicable</h2><p>El resumen muestra lo esencial y el análisis detalla elevación, consumo por segmento y factores aplicados.</p></article><article><span>03</span><h2>Costos de API controlados</h2><p>El servidor bloquea servicios pagados de elevación y clima; utiliza Open-Meteo sin facturación automática.</p></article></section>
  <section className="about-method"><div><span>Metodología</span><h2>Cómo construimos la estimación</h2></div><ol><li><b>Base contextual</b><p>Parte del dato estándar o del rendimiento informado y lo adapta a ciudad, uso mixto, carretera o camino rural.</p></li><li><b>Ruta segmentada</b><p>Distribuye distancia, pendiente y elevación para estimar el consumo de cada tramo.</p></li><li><b>Condiciones de operación</b><p>Aplica carga, pasajeros, clima, tráfico por horario, arranque en frío y ritmo de conducción.</p></li><li><b>Resultado trazable</b><p>Expone las métricas y factores utilizados para que la estimación pueda revisarse y compararse.</p></li></ol></section>
  <section className="about-stack"><div><span>Tecnología</span><h2>Arquitectura full-stack</h2><p>React y Vite en el cliente; Flask, SQLAlchemy y PostgreSQL en el backend. Open-Meteo aporta clima y elevación sin facturación automática.</p></div><div className="stack-tags"><span>React</span><span>Vite</span><span>Flask</span><span>PostgreSQL</span><span>Open-Meteo</span><span>JWT</span></div></section>
  <aside className="about-disclaimer"><strong>Transparencia del modelo</strong><p>El resultado es una estimación, no una medición certificada. La congestión en tiempo real, velocidad efectiva, presión de neumáticos, estado mecánico y hábitos reales pueden modificar el consumo observado.</p></aside>
</div>;

export default About;
