"""preparar identidad multi proveedor y verificacion de correo

Revision ID: 0510592fcee5
Revises: f6cacdc492cb
Create Date: 2026-09-28 17:24:43.736094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0510592fcee5'
down_revision = 'f6cacdc492cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Las FK hacia user.id de auth_identity y verification_token NO usan
    # ondelete="CASCADE" -- decisión deliberada, coherente con trip.user_id
    # y revoked_token.user_id, que tampoco lo usan en la migración inicial.
    # El cascade al eliminar un User se maneja exclusivamente a nivel de
    # ORM (SQLAlchemy cascade="all, delete" en backend/models.py), no a
    # nivel de PostgreSQL. Ver el comentario junto a User.auth_identities
    # en models.py para el razonamiento completo.
    op.create_table('auth_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=120), nullable=True),
    # server_default=false por coherencia con user.email_verified más abajo
    # (mismo patrón: booleano NOT NULL que representa un hecho no ocurrido
    # todavía por defecto). No es obligatorio para que este CREATE TABLE
    # funcione -- es una tabla nueva, sin filas que backfillear -- pero
    # evita que un INSERT directo a nivel de DB que omita esta columna
    # falle por violar NOT NULL, en vez de depender únicamente del
    # default=False del lado Python/ORM.
    sa.Column('provider_email_verified', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_auth_identity_provider_subject')
    )
    with op.batch_alter_table('auth_identity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_identity_user_id'), ['user_id'], unique=False)

    op.create_table('verification_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('verification_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_token_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        # server_default=false es obligatorio aquí: la columna es NOT NULL y
        # la tabla ya tiene filas (usuarios existentes). Sin un default a
        # nivel de base de datos, el ALTER TABLE fallaría al no saber qué
        # valor asignar a esas filas. Ninguna fila existente pasa a True --
        # nunca verificaron su correo realmente, así que quedan en False,
        # que es exactamente lo que representa ese valor.
        #
        # El server_default se deja PERMANENTE (no se retira después de
        # aplicar la migración): sirve como red de seguridad a nivel de base
        # de datos ante cualquier INSERT que no pase por el modelo de
        # SQLAlchemy (que ya tiene su propio default=False del lado
        # Python). Es inocuo mantenerlo -- no fuerza ningún valor futuro,
        # solo cubre el caso de que la columna se omita explícitamente.
        batch_op.add_column(
            sa.Column(
                'email_verified',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(), nullable=True))
        # Habilita password NULL para cuentas creadas exclusivamente por un
        # proveedor externo (Google y, más adelante, otros). El registro
        # tradicional (auth_routes.py) no cambia en este checkpoint y sigue
        # exigiendo contraseña -- este ALTER solo hace posible el caso sin
        # contraseña a nivel de esquema, no lo activa en ningún endpoint.
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # LIMITACIÓN CONOCIDA: si para cuando se ejecute este downgrade ya
    # existe algún usuario con password IS NULL (p. ej. una cuenta creada
    # solo con Google en un checkpoint posterior), este ALTER fallará --
    # Postgres no permite volver a NOT NULL una columna con filas NULL.
    # HOY (en este checkpoint) es seguro: todavía no se crea ningún usuario
    # sin contraseña en ningún flujo real.
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('verification_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_token_user_id'))

    op.drop_table('verification_token')
    with op.batch_alter_table('auth_identity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_identity_user_id'))

    op.drop_table('auth_identity')
    # ### end Alembic commands ###
