"""add expected and real consumption to trip

Revision ID: 2831dcf82e76
Revises: 45ebd6463030
Create Date: 2026-01-20 23:27:10.459501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2831dcf82e76'
down_revision = '45ebd6463030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_consumption', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('real_consumption', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('real_consumption')
        batch_op.drop_column('expected_consumption')

    # ### end Alembic commands ###
