"""store adjusted consumption for calibration

Revision ID: 45ebd6463030
Revises: 655e3e827e0d
Create Date: 2026-01-19 10:47:51.490225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ebd6463030'
down_revision = '655e3e827e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adjusted_consumption', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calibration_factor_used', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('calibration_factor_used')
        batch_op.drop_column('adjusted_consumption')

    # ### end Alembic commands ###
