"""add session_version and revoked_token

Revision ID: 87784dde05d6
Revises: f14c83d9a426
Create Date: 2026-09-15 19:49:33.603763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87784dde05d6'
down_revision = 'f14c83d9a426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_token_jti'), ['jti'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'session_version', sa.Integer(), nullable=False, server_default='0'
        ))

    # ### end Alembic commands ###
    # NOTE: an unrelated drift on 'trip.expected_consumption' (nullable in the
    # live dev DB vs NOT NULL in the model) was detected by autogenerate and
    # intentionally removed from this migration — it's pre-existing and out of
    # scope for the session_version/revoked_token change.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_token_jti'))

    op.drop_table('revoked_token')
    # ### end Alembic commands ###
