"""Corrigiendo modelos

Revision ID: e0639f1e7b16
Revises: ac20e22451fa
Create Date: 2025-03-07 22:03:09.285499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0639f1e7b16'
down_revision = 'ac20e22451fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=True),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('engine_cylinders', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=True),
    sa.Column('lkm_mixed', sa.Float(), nullable=True),
    sa.Column('mpg_mixed', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('model')
    op.drop_table('brand')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('brand_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='brand_pkey'),
    sa.UniqueConstraint('name', name='brand_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name='model_brand_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='model_pkey')
    )
    op.drop_table('vehicle')
    # ### end Alembic commands ###
