"""Add extended fields to Trip model

Revision ID: e18307b0bd80
Revises: 
Create Date: 2025-03-25 15:37:04.235388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18307b0bd80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fuel_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('passengers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('road_grade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weather', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_column('weather')
        batch_op.drop_column('road_grade')
        batch_op.drop_column('passengers')
        batch_op.drop_column('total_weight')
        batch_op.drop_column('fuel_price')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
