"""Initial schema

Revision ID: f6cacdc492cb
Revises: 
Create Date: 2026-09-17 00:09:49.593798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cacdc492cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('engine_cc', sa.Integer(), nullable=True),
    sa.Column('engine_cylinders', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Integer(), nullable=False),
    sa.Column('lkm_mixed', sa.Float(), nullable=True),
    sa.Column('lkm_highway', sa.Float(), nullable=True),
    sa.Column('mpg_mixed', sa.Float(), nullable=True),
    sa.Column('drive_type', sa.String(length=20), nullable=True),
    sa.Column('transmission', sa.String(length=20), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('calibration_factor', sa.Float(), nullable=False),
    sa.Column('calibration_samples', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make', 'model', 'year', name='uq_vehicle_make_model_year')
    )
    op.create_table('revoked_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_token_jti'), ['jti'], unique=True)

    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('fuel_price', sa.Float(), nullable=True),
    sa.Column('fuel_octane', sa.String(length=20), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('origin_label', sa.String(length=255), nullable=True),
    sa.Column('destination_label', sa.String(length=255), nullable=True),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('road_grade', sa.Float(), nullable=False),
    sa.Column('road_profile', sa.String(length=20), nullable=False),
    sa.Column('driving_style', sa.String(length=20), nullable=False),
    sa.Column('weather', sa.String(length=50), nullable=False),
    sa.Column('consumption_type', sa.String(length=20), nullable=True),
    sa.Column('base_consumption', sa.Float(), nullable=True),
    sa.Column('expected_consumption', sa.Float(), nullable=False),
    sa.Column('adjusted_consumption', sa.Float(), nullable=True),
    sa.Column('calibration_factor_used', sa.Float(), nullable=True),
    sa.Column('real_consumption', sa.Float(), nullable=True),
    sa.Column('user_consumption_kml', sa.Float(), nullable=True),
    sa.Column('consumption_reference_profile', sa.String(length=20), nullable=True),
    sa.Column('consumption_source', sa.String(length=20), nullable=False),
    sa.Column('elevation_profile', sa.JSON(), nullable=True),
    sa.Column('consumption_profile', sa.JSON(), nullable=True),
    sa.Column('elevation_source', sa.String(length=50), nullable=True),
    sa.Column('segments_analyzed', sa.Integer(), nullable=True),
    sa.Column('operating_conditions', sa.JSON(), nullable=True),
    sa.Column('fuel_consumed', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('user_vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_vehicle')
    op.drop_table('user_role')
    op.drop_table('trip')
    with op.batch_alter_table('revoked_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_token_jti'))

    op.drop_table('revoked_token')
    op.drop_table('vehicle')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
